name:             hspec-meta
version:          2.4.3
license:          MIT
copyright:
  - (c) 2011-2017 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
maintainer:       Simon Hengel <sol@typeful.net>
category:         Testing
stability:        experimental
homepage:         http://hspec.github.io/
synopsis:         A version of Hspec which is used to test Hspec itself
description: |
  A stable version of Hspec which is used to test the
  in-development version of Hspec.

extra-source-files: CHANGES.markdown

github: hspec/hspec

ghc-options: -Wall

dependencies:
  - base == 4.*
  - transformers >= 0.2.2.0
  - QuickCheck >= 2.5.1

  - hspec-expectations
  - HUnit
  - setenv
  - deepseq
  - random
  - quickcheck-io
  - ansi-terminal
  - time
  - async
  - call-stack
  - filepath
  - directory
  - clock

  - array # for Diff

library:
  source-dirs:
    - src
    - hspec-core/src
    - hspec-core/vendor
  exposed-modules:
    - Test.Hspec.Meta

executables:
  hspec-meta-discover:
    source-dirs:
      - hspec-discover/src
      - hspec-discover/driver
    main: hspec-discover.hs
    dependencies:
      - filepath
      - directory
